AllCops:
  Exclude:
    - vendor/**/*

Encoding:
  Enabled: false
Documentation:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
RedundantReturn:
  Enabled: false
AndOr:
  Enabled: false
MethodLength:
  Max: 25
Style/RegexpLiteral:
  MaxSlashes: 0
